### PR TITLE
Update Android plugin to use latest GooglePlayServices libraries

### PR DESCRIPTION
**Pull request by rhishikeshj**
This PR will update the Gcm and Base play services libraries to the latest available versions : 42.1001.0 and will also change the required code for referencing Gms.Iid
This change is required if we want to use this plugin in any new project since the versions being used currently in the plugin are outdated.

### CODE REVIEW

**Comment by rhishikeshj** [comment]
Build errors on AppVeyor are due to it not being able to find NewtonSoft.Json

`C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Newtonsoft.Json". Check to make sure the assembly exists on disk. `

**Review by rdelrosario — COMMENTED** [review]
Thanks for you contribution. I will test this, if everything fine will update the NuGet package.

**Comment by rdelrosario** [comment]
Try this prerelease: https://www.nuget.org/packages/Xam.Plugin.PushNotification/1.2.5-beta let me know if everything ok if so will release an oficial version.

**Comment by rhishikeshj** [comment]
@rdelrosario Thanks ! I will give this a go over the weekend and let you know the results.
I am also looking at trying to add in cross platform FCM support.
Any thoughts on this ? Or how I should approach integrating that with this plugin and its API ?

**Comment by rdelrosario** [comment]
Hi

I guess this will be a good start:

https://developers.google.com/cloud-messaging/android/android-migrate-fcm

If you will migrate GCM to FCM. But if is to support FCM also on iOS then we might require to define an extra abstraction layer so that the user can choose on iOS to use FCM or not. I don't have any concrete ideas yet but will think about it.

**Pull request merged**
