### PR TITLE
Added UWP package

### PR DESCRIPTION
**Pull request by dimitrijevic**
Changed namespace (as per Montemagno's recent recommendations)
Plugin.DeviceMotion
This isn't fully tested (it builds fine)
About to test it more
I'd like 2nd opinion 2
Should version be 1.1 or 2.0 (given namespace change)?

### CODE REVIEW

**Comment by rdelrosario** [comment]
Yes could be 2.0

**Comment by rdelrosario** [comment]
Let me know when you tested fully, will do too when i got time. But looks fine to me so far

**Comment by dimitrijevic** [comment]
Sorry it took a while to test, I ran into some problems referencing it as a project being built from source code into a UWP project (_Payload contains two or more files with the same destination path DeviceMotion.Plugin.dll / pdb_ which I still can't figure out how to solve since suggested copy local false wouldn't work for me)...so I built a nuget package and installed it from a local package source in my UWP test project...and for the most part it works on an W10M ARM device (my Windows tablet is still on 8.1, so I'll be able to test it on x86 next week maybe when I switch to W10, but I think it should work as long as the device has an accelerometer which worked fine on ARM). 

After more consideration I propose namespace 'Plugin.DeviceMotion' for 2.0 (as that's a breaking change) along with maybe a sensor fusion implementation or other new features (got suggestions?)...I'd love to do it, but I'm swamped now...I did found a problem running on Windows Phone 8/8.1 when the device only has an accelerometer, so I added a try catch to patch it, but strangely it worked without that on same device under W10M, I'd love to understand why but can't wrap my head around it...version 1.1?

What I also noticed was a problem which could be due to something I missed in reverting namespaces and version number setting in the nuget file is that the dlls in the UWP project seem not to have a version number set (it says 0.0.0.0), so could you maybe build your own DeviceMotion nuget for the weekend and publish it as a prerelease 1.1.0 so I could verify that's a problem not just occurring on my machine (I'd love to know what I've missed and could correct in that payload and this version error).TIA

**Comment by dimitrijevic** [comment]
Would you need me to rebase all my commits onto the last commit, or can you just use as is, 'cause when I noticed the error which occurred on WP8/8.1 with non-gyroscope enabled devices I accidentally committed the test project I noticed that problem on, it's removed in the latest commit. Hope it's ok...

EDIT: I just figured out what's the solution to that payload problem, it was due to the fact that the portable project was referencing a nuget and the universal project was referencing the plugin from source code...for some reason, although both dll versions are seemingly the same, VS can't remove duplicate dlls in the universal project but didn't have a problem with winphone version...x86 still untested.

**Comment by dimitrijevic** [comment]
Tested on x86, works fine, 1.1.0-alpha...not 0.0.0.0...as a nuget (https://www.nuget.org/packages/Xam.DeviceMotion.Plugin/1.1.0-alpha - I'll remove it afterwards, as soon as you publish 1.1.0)

**Comment by JanNepras** [comment]
@dimitrijevic were you able to resolve issue "Payload contains two or more files with the same destination path ". I have this in my build definition and I don't know how to fix it.

**Comment by dimitrijevic** [comment]
Yes, trough workaround, by deleting reference...think it was that...I'll get back to you, if it is not, think it was.

Also, it might help, to get onto newer runtimes, for UWP I mean, they're improving...

That's the nuget which started as 5.x....I think they're up to 5.4 at least now...the last time I checked.

**Pull request merged**
